---
- name: Deploy Student Course Portal on EC2
  hosts: web
  become: yes

  vars:
    repo_url: "https://github.com/Hemalathaboddula/Student-course-portal.git"
    dest_path: "/var/www/html"

  tasks:

    #  Install required packages
    - name: Install required packages
      apt:
        name:
          - nginx
          - git
          - python3-pip
          - python3-venv
        state: present
        update_cache: yes

    #  Start nginx
    - name: Start and enable nginx
      service:
        name: nginx
        state: started
        enabled: yes

    #  Remove old code
    - name: Remove old app
      file:
        path: "{{ dest_path }}"
        state: absent

    #  Clone repo
    - name: Clone Student Course Portal repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ dest_path }}"
        version: master
        force: yes

    #  Create virtual environment
    - name: Create virtualenv
      command: python3 -m venv venv
      args:
        chdir: "{{ dest_path }}"

    #  Install requirements
    - name: Install Python dependencies
      pip:
        requirements: "{{ dest_path }}/requirements.txt"
        virtualenv: "{{ dest_path }}/venv"

    #  Run migrations
    - name: Run migrations
      command: "{{ dest_path }}/venv/bin/python manage.py migrate"
      args:
        chdir: "{{ dest_path }}"

    #  ADD HERE (THIS IS YOUR QUESTION ANSWER)
    - name: Load initial data
      command: "{{ dest_path }}/venv/bin/python manage.py loaddata courses"
      args:
        chdir: "{{ dest_path }}"
      ignore_errors: yes

    # Collect static files
    - name: Collect static files
      command: "{{ dest_path }}/venv/bin/python manage.py collectstatic --noinput"
      args:
        chdir: "{{ dest_path }}"

    #  Start Gunicorn
    - name: Start Gunicorn
      shell: "{{ dest_path }}/venv/bin/gunicorn --daemon --bind 0.0.0.0:8000 learnhub.wsgi:application"
      args:
        chdir: "{{ dest_path }}"

    #  Restart nginx
    - name: Restart nginx
      service:
        name: nginx
        state: restarted
