---
- name: Deploy Django Student Portal
  hosts: web
  become: yes

  vars:
    app_dir: /home/ec2-user/app
    repo_url: https://github.com/Hemalathaboddula/Student-course-portal.git

  tasks:

    - name: Install packages
      yum:
        name:
          - git
          - python3
          - python3-pip
          - nginx
        state: present

    - name: Remove old app
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"

    - name: Install Python dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"

    - name: Install Gunicorn
      pip:
        name: gunicorn

    - name: Run migrations
      command: python3 manage.py migrate
      args:
        chdir: "{{ app_dir }}"

    # ✅ SYSTEMD SERVICE (BEST WAY)
    - name: Create Gunicorn service
      copy:
        dest: /etc/systemd/system/django.service
        content: |
          [Unit]
          Description=Django App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory={{ app_dir }}
          ExecStart=/usr/local/bin/gunicorn learnhub.wsgi:application --bind 127.0.0.1:8000
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Restart systemd
      command: systemctl daemon-reexec

    - name: Enable and start Django service
      systemd:
        name: django
        enabled: yes
        state: restarted

    # ✅ NGINX CONFIG
    - name: Configure nginx
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          events {}
          http {
            server {
              listen 80;
              location / {
                proxy_pass http://127.0.0.1:8000;
              }
            }
          }

    - name: Restart nginx
      service:
        name: nginx
        state: restarted