- name: Deploy Django Student Portal
  hosts: web
  become: yes

  vars:
    app_dir: /home/ec2-user/app
    repo_url: https://github.com/Hemalathaboddula/Student-course-portal.git

  tasks:

    - name: Install packages
      yum:
        name:
          - git
          - python3
          - python3-pip
          - nginx
        state: present

    - name: Remove old app
      file:
        path: "{{ app_dir }}"
        state: absent

    - name: Clone repo
      git:
        repo: "{{ repo_url }}"
        dest: "{{ app_dir }}"

    - name: Create virtual environment
      command: python3 -m venv {{ app_dir }}/venv

    - name: Install dependencies
      pip:
        requirements: "{{ app_dir }}/requirements.txt"
        virtualenv: "{{ app_dir }}/venv"

    - name: Run migrations
      command: "{{ app_dir }}/venv/bin/python manage.py migrate"
      args:
        chdir: "{{ app_dir }}"

    - name: Collect static files
      command: "{{ app_dir }}/venv/bin/python manage.py collectstatic --noinput"
      args:
        chdir: "{{ app_dir }}"

    - name: Create Gunicorn service
      copy:
        dest: /etc/systemd/system/django.service
        content: |
          [Unit]
          Description=Django App
          After=network.target

          [Service]
          User=ec2-user
          WorkingDirectory={{ app_dir }}
          ExecStart={{ app_dir }}/venv/bin/gunicorn learnhub.wsgi:application --bind 127.0.0.1:8000
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Reload systemd
      command: systemctl daemon-reload

    - name: Start Django service
      systemd:
        name: django
        enabled: yes
        state: started

    - name: Configure nginx
      copy:
        dest: /etc/nginx/nginx.conf
        content: |
          events {}
          http {
            server {
              listen 80;

              location / {
                proxy_pass http://127.0.0.1:8000;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
              }
            }
          }

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
